version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dealnews_mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:4.8.1
    container_name: dealnews_adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  scraper:
    build: .
    container_name: dealnews_scraper
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
    volumes:
      - ./exports:/app/exports
    depends_on:
      - mysql
    command: ["python", "run.py"]

volumes:
  mysql_data: